<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE conjugaison [
	<!ELEMENT conjugaison (template+)>
	<!ELEMENT template (infinitif?, indicatif?, conditionnel?, subjonctif?, imperatif?, participe?)>
	<!ATTLIST template name CDATA #REQUIRED>

	<!ELEMENT infinitif (present)>
	<!ELEMENT indicatif (present, imparfait, futur, passe-simple)>
	<!ELEMENT conditionnel (present)>
	<!ELEMENT subjonctif (present, imparfait)>
	<!ELEMENT imperatif (present)>
	<!ELEMENT participe (present, passe)>

	<!ELEMENT present (p, p?, p?, p?, p?, p?)>
	<!ELEMENT imparfait (p, p?, p?, p?, p?, p?)>
	<!ELEMENT futur (p, p?, p?, p?, p?, p?)>
	<!ELEMENT passe-simple (p, p?, p?, p?, p?, p?)>
	<!ELEMENT passe (p, p, p, p)>

	<!ELEMENT p (i*)>
	<!ELEMENT i (#PCDATA)>
]>

<conjugaison>

<template name="pla:cer">
	<infinitif>
		<present>
			<p><i>cer</i></p>
		</present>
	</infinitif>
	<indicatif>
		<present>
			<p><i>ce</i></p>
			<p><i>ces</i></p>
			<p><i>ce</i></p>
			<p><i>çons</i></p>
			<p><i>cez</i></p>
			<p><i>cent</i></p>
		</present>
		<imparfait>
			<p><i>çais</i></p>
			<p><i>çais</i></p>
			<p><i>çait</i></p>
			<p><i>cions</i></p>
			<p><i>ciez</i></p>
			<p><i>çaient</i></p>
		</imparfait>
		<futur>
			<p><i>cerai</i></p>
			<p><i>ceras</i></p>
			<p><i>cera</i></p>
			<p><i>cerons</i></p>
			<p><i>cerez</i></p>
			<p><i>ceront</i></p>
		</futur>
		<passe-simple>
			<p><i>çai</i></p>
			<p><i>ças</i></p>
			<p><i>ça</i></p>
			<p><i>çâmes</i></p>
			<p><i>çâtes</i></p>
			<p><i>cèrent</i></p>
		</passe-simple>
	</indicatif>
	<conditionnel>
		<present>
			<p><i>cerais</i></p>
			<p><i>cerais</i></p>
			<p><i>cerait</i></p>
			<p><i>cerions</i></p>
			<p><i>ceriez</i></p>
			<p><i>ceraient</i></p>
		</present>
	</conditionnel>
	<subjonctif>
		<present>
			<p><i>ce</i></p>
			<p><i>ces</i></p>
			<p><i>ce</i></p>
			<p><i>cions</i></p>
			<p><i>ciez</i></p>
			<p><i>cent</i></p>
		</present>
		<imparfait>
			<p><i>çasse</i></p>
			<p><i>çasses</i></p>
			<p><i>çât</i></p>
			<p><i>çassions</i></p>
			<p><i>çassiez</i></p>
			<p><i>çassent</i></p>
		</imparfait>
	</subjonctif>
	<imperatif>
		<present>
			<p><i>ce</i></p>
			<p><i>çons</i></p>
			<p><i>cez</i></p>
		</present>
	</imperatif>
	<participe>
		<present>
			<p><i>çant</i></p>
		</present>
		<passe>
			<p><i>cé</i></p>
			<p><i>cés</i></p>
			<p><i>cée</i></p>
			<p><i>cées</i></p>
		</passe>
	</participe>
</template>

<template name="dép:ecer">
	<infinitif>
		<present>
			<p><i>ecer</i></p>
		</present>
	</infinitif>
	<indicatif>
		<present>
			<p><i>ece</i><i>èce</i></p>
			<p><i>eces</i><i>èces</i></p>
			<p><i>ece</i><i>èce</i></p>
			<p><i>eçons</i></p>
			<p><i>ecez</i></p>
			<p><i>ecent</i><i>ècent</i></p>
		</present>
		<imparfait>
			<p><i>eçais</i></p>
			<p><i>eçais</i></p>
			<p><i>eçait</i></p>
			<p><i>ecions</i></p>
			<p><i>eciez</i></p>
			<p><i>eçaient</i></p>
		</imparfait>
		<futur>
			<p><i>ecerai</i><i>ècerai</i></p>
			<p><i>eceras</i><i>èceras</i></p>
			<p><i>ecera</i><i>ècera</i></p>
			<p><i>ecerons</i><i>ècerons</i></p>
			<p><i>ecerez</i><i>ècerez</i></p>
			<p><i>eceront</i><i>èceront</i></p>
		</futur>
		<passe-simple>
			<p><i>eçai</i></p>
			<p><i>eças</i></p>
			<p><i>eça</i></p>
			<p><i>eçâmes</i></p>
			<p><i>eçâtes</i></p>
			<p><i>ecèrent</i></p>
		</passe-simple>
	</indicatif>
	<conditionnel>
		<present>
			<p><i>ecerais</i><i>ècerais</i></p>
			<p><i>ecerais</i><i>ècerais</i></p>
			<p><i>ecerait</i><i>ècerait</i></p>
			<p><i>ecerions</i><i>ècerions</i></p>
			<p><i>eceriez</i><i>èceriez</i></p>
			<p><i>eceraient</i><i>èceraient</i></p>
		</present>
	</conditionnel>
	<subjonctif>
		<present>
			<p><i>ece</i><i>èce</i></p>
			<p><i>eces</i><i>èces</i></p>
			<p><i>ece</i><i>èce</i></p>
			<p><i>ecions</i></p>
			<p><i>eciez</i></p>
			<p><i>ecent</i><i>ècent</i></p>
		</present>
		<imparfait>
			<p><i>eçasse</i></p>
			<p><i>eçasses</i></p>
			<p><i>eçât</i></p>
			<p><i>eçassions</i></p>
			<p><i>eçassiez</i></p>
			<p><i>eçassent</i></p>
		</imparfait>
	</subjonctif>
	<imperatif>
		<present>
			<p><i>ece</i><i>èce</i></p>
			<p><i>eçons</i></p>
			<p><i>ecez</i></p>
		</present>
	</imperatif>
	<participe>
		<present>
			<p><i>eçant</i></p>
		</present>
		<passe>
			<p><i>ecé</i></p>
			<p><i>ecés</i></p>
			<p><i>ecée</i></p>
			<p><i>ecées</i></p>
		</passe>
	</participe>
</template>

<template name="man:ger">
	<infinitif>
		<present>
			<p><i>ger</i></p>
		</present>
	</infinitif>
	<indicatif>
		<present>
			<p><i>ge</i></p>
			<p><i>ges</i></p>
			<p><i>ge</i></p>
			<p><i>geons</i></p>
			<p><i>gez</i></p>
			<p><i>gent</i></p>
		</present>
		<imparfait>
			<p><i>geais</i></p>
			<p><i>geais</i></p>
			<p><i>geait</i></p>
			<p><i>gions</i></p>
			<p><i>giez</i></p>
			<p><i>geaient</i></p>
		</imparfait>
		<futur>
			<p><i>gerai</i></p>
			<p><i>geras</i></p>
			<p><i>gera</i></p>
			<p><i>gerons</i></p>
			<p><i>gerez</i></p>
			<p><i>geront</i></p>
		</futur>
		<passe-simple>
			<p><i>geai</i></p>
			<p><i>geas</i></p>
			<p><i>gea</i></p>
			<p><i>geâmes</i></p>
			<p><i>geâtes</i></p>
			<p><i>gèrent</i></p>
		</passe-simple>
	</indicatif>
	<conditionnel>
		<present>
			<p><i>gerais</i></p>
			<p><i>gerais</i></p>
			<p><i>gerait</i></p>
			<p><i>gerions</i></p>
			<p><i>geriez</i></p>
			<p><i>geraient</i></p>
		</present>
	</conditionnel>
	<subjonctif>
		<present>
			<p><i>ge</i></p>
			<p><i>ges</i></p>
			<p><i>ge</i></p>
			<p><i>gions</i></p>
			<p><i>giez</i></p>
			<p><i>gent</i></p>
		</present>
		<imparfait>
			<p><i>geasse</i></p>
			<p><i>geasses</i></p>
			<p><i>geât</i></p>
			<p><i>geassions</i></p>
			<p><i>geassiez</i></p>
			<p><i>geassent</i></p>
		</imparfait>
	</subjonctif>
	<imperatif>
		<present>
			<p><i>ge</i></p>
			<p><i>geons</i></p>
			<p><i>gez</i></p>
		</present>
	</imperatif>
	<participe>
		<present>
			<p><i>geant</i></p>
		</present>
		<passe>
			<p><i>gé</i></p>
			<p><i>gés</i></p>
			<p><i>gée</i></p>
			<p><i>gées</i></p>
		</passe>
	</participe>
</template>

<template name="pa:yer">
	<infinitif>
		<present>
			<p><i>yer</i></p>
		</present>
	</infinitif>
	<indicatif>
		<present>
			<p><i>ie</i><i>ye</i></p>
			<p><i>ies</i><i>yes</i></p>
			<p><i>ie</i><i>ye</i></p>
			<p><i>yons</i></p>
			<p><i>yez</i></p>
			<p><i>ient</i><i>yent</i></p>
		</present>
		<imparfait>
			<p><i>yais</i></p>
			<p><i>yais</i></p>
			<p><i>yait</i></p>
			<p><i>yions</i></p>
			<p><i>yiez</i></p>
			<p><i>yaient</i></p>
		</imparfait>
		<futur>
			<p><i>ierai</i><i>yerai</i></p>
			<p><i>ieras</i><i>yeras</i></p>
			<p><i>iera</i><i>yera</i></p>
			<p><i>ierons</i><i>yerons</i></p>
			<p><i>ierez</i><i>yerez</i></p>
			<p><i>ieront</i><i>yeront</i></p>
		</futur>
		<passe-simple>
			<p><i>yai</i></p>
			<p><i>yas</i></p>
			<p><i>ya</i></p>
			<p><i>yâmes</i></p>
			<p><i>yâtes</i></p>
			<p><i>yèrent</i></p>
		</passe-simple>
	</indicatif>
	<conditionnel>
		<present>
			<p><i>ierais</i><i>yerais</i></p>
			<p><i>ierais</i><i>yerais</i></p>
			<p><i>ierait</i><i>yerait</i></p>
			<p><i>ierions</i><i>yerions</i></p>
			<p><i>ieriez</i><i>yeriez</i></p>
			<p><i>ieraient</i><i>yeraient</i></p>
		</present>
	</conditionnel>
	<subjonctif>
		<present>
			<p><i>ie</i><i>ye</i></p>
			<p><i>ies</i><i>yes</i></p>
			<p><i>ie</i><i>ye</i></p>
			<p><i>yions</i></p>
			<p><i>yiez</i></p>
			<p><i>ient</i><i>yent</i></p>
		</present>
		<imparfait>
			<p><i>yasse</i></p>
			<p><i>yasses</i></p>
			<p><i>yât</i></p>
			<p><i>yassions</i></p>
			<p><i>yassiez</i></p>
			<p><i>yassent</i></p>
		</imparfait>
	</subjonctif>
	<imperatif>
		<present>
			<p><i>ie</i><i>ye</i></p>
			<p><i>yons</i></p>
			<p><i>yez</i></p>
		</present>
	</imperatif>
	<participe>
		<present>
			<p><i>yant</i></p>
		</present>
		<passe>
			<p><i>yé</i></p>
			<p><i>yés</i></p>
			<p><i>yée</i></p>
			<p><i>yées</i></p>
		</passe>
	</participe>
</template>

<template name="netto:yer">
	<infinitif>
		<present>
			<p><i>yer</i></p>
		</present>
	</infinitif>
	<indicatif>
		<present>
			<p><i>ie</i></p>
			<p><i>ies</i></p>
			<p><i>ie</i></p>
			<p><i>yons</i></p>
			<p><i>yez</i></p>
			<p><i>ient</i></p>
		</present>
		<imparfait>
			<p><i>yais</i></p>
			<p><i>yais</i></p>
			<p><i>yait</i></p>
			<p><i>yions</i></p>
			<p><i>yiez</i></p>
			<p><i>yaient</i></p>
		</imparfait>
		<futur>
			<p><i>ierai</i></p>
			<p><i>ieras</i></p>
			<p><i>iera</i></p>
			<p><i>ierons</i></p>
			<p><i>ierez</i></p>
			<p><i>ieront</i></p>
		</futur>
		<passe-simple>
			<p><i>yai</i></p>
			<p><i>yas</i></p>
			<p><i>ya</i></p>
			<p><i>yâmes</i></p>
			<p><i>yâtes</i></p>
			<p><i>yèrent</i></p>
		</passe-simple>
	</indicatif>
	<conditionnel>
		<present>
			<p><i>ierais</i></p>
			<p><i>ierais</i></p>
			<p><i>ierait</i></p>
			<p><i>ierions</i></p>
			<p><i>ieriez</i></p>
			<p><i>ieraient</i></p>
		</present>
	</conditionnel>
	<subjonctif>
		<present>
			<p><i>ie</i></p>
			<p><i>ies</i></p>
			<p><i>ie</i></p>
			<p><i>yions</i></p>
			<p><i>yiez</i></p>
			<p><i>ient</i></p>
		</present>
		<imparfait>
			<p><i>yasse</i></p>
			<p><i>yasses</i></p>
			<p><i>yât</i></p>
			<p><i>yassions</i></p>
			<p><i>yassiez</i></p>
			<p><i>yassent</i></p>
		</imparfait>
	</subjonctif>
	<imperatif>
		<present>
			<p><i>ie</i></p>
			<p><i>yons</i></p>
			<p><i>yez</i></p>
		</present>
	</imperatif>
	<participe>
		<present>
			<p><i>yant</i></p>
		</present>
		<passe>
			<p><i>yé</i></p>
			<p><i>yés</i></p>
			<p><i>yée</i></p>
			<p><i>yées</i></p>
		</passe>
	</participe>
</template>

<template name="grasse:yer">
	<infinitif>
		<present>
			<p><i>yer</i></p>
		</present>
	</infinitif>
	<indicatif>
		<present>
			<p><i>ye</i></p>
			<p><i>yes</i></p>
			<p><i>ye</i></p>
			<p><i>yons</i></p>
			<p><i>yez</i></p>
			<p><i>yent</i></p>
		</present>
		<imparfait>
			<p><i>yais</i></p>
			<p><i>yais</i></p>
			<p><i>yait</i></p>
			<p><i>yions</i></p>
			<p><i>yiez</i></p>
			<p><i>yaient</i></p>
		</imparfait>
		<futur>
			<p><i>yerai</i></p>
			<p><i>yeras</i></p>
			<p><i>yera</i></p>
			<p><i>yerons</i></p>
			<p><i>yerez</i></p>
			<p><i>yeront</i></p>
		</futur>
		<passe-simple>
			<p><i>yai</i></p>
			<p><i>yas</i></p>
			<p><i>ya</i></p>
			<p><i>yâmes</i></p>
			<p><i>yâtes</i></p>
			<p><i>yèrent</i></p>
		</passe-simple>
	</indicatif>
	<conditionnel>
		<present>
			<p><i>yerais</i></p>
			<p><i>yerais</i></p>
			<p><i>yerait</i></p>
			<p><i>yerions</i></p>
			<p><i>yeriez</i></p>
			<p><i>yeraient</i></p>
		</present>
	</conditionnel>
	<subjonctif>
		<present>
			<p><i>ye</i></p>
			<p><i>yes</i></p>
			<p><i>ye</i></p>
			<p><i>yions</i></p>
			<p><i>yiez</i></p>
			<p><i>yent</i></p>
		</present>
		<imparfait>
			<p><i>yasse</i></p>
			<p><i>yasses</i></p>
			<p><i>yât</i></p>
			<p><i>yassions</i></p>
			<p><i>yassiez</i></p>
			<p><i>yassent</i></p>
		</imparfait>
	</subjonctif>
	<imperatif>
		<present>
			<p><i>ye</i></p>
			<p><i>yons</i></p>
			<p><i>yez</i></p>
		</present>
	</imperatif>
	<participe>
		<present>
			<p><i>yant</i></p>
		</present>
		<passe>
			<p><i>yé</i></p>
			<p><i>yés</i></p>
			<p><i>yée</i></p>
			<p><i>yées</i></p>
		</passe>
	</participe>
</template>

<template name="app:eler">
	<infinitif>
		<present>
			<p><i>eler</i></p>
		</present>
	</infinitif>
	<indicatif>
		<present>
			<p><i>elle</i></p>
			<p><i>elles</i></p>
			<p><i>elle</i></p>
			<p><i>elons</i></p>
			<p><i>elez</i></p>
			<p><i>ellent</i></p>
		</present>
		<imparfait>
			<p><i>elais</i></p>
			<p><i>elais</i></p>
			<p><i>elait</i></p>
			<p><i>elions</i></p>
			<p><i>eliez</i></p>
			<p><i>elaient</i></p>
		</imparfait>
		<futur>
			<p><i>ellerai</i></p>
			<p><i>elleras</i></p>
			<p><i>ellera</i></p>
			<p><i>ellerons</i></p>
			<p><i>ellerez</i></p>
			<p><i>elleront</i></p>
		</futur>
		<passe-simple>
			<p><i>elai</i></p>
			<p><i>elas</i></p>
			<p><i>ela</i></p>
			<p><i>elâmes</i></p>
			<p><i>elâtes</i></p>
			<p><i>elèrent</i></p>
		</passe-simple>
	</indicatif>
	<conditionnel>
		<present>
			<p><i>ellerais</i></p>
			<p><i>ellerais</i></p>
			<p><i>ellerait</i></p>
			<p><i>ellerions</i></p>
			<p><i>elleriez</i></p>
			<p><i>elleraient</i></p>
		</present>
	</conditionnel>
	<subjonctif>
		<present>
			<p><i>elle</i></p>
			<p><i>elles</i></p>
			<p><i>elle</i></p>
			<p><i>elions</i></p>
			<p><i>eliez</i></p>
			<p><i>ellent</i></p>
		</present>
		<imparfait>
			<p><i>elasse</i></p>
			<p><i>elasses</i></p>
			<p><i>elât</i></p>
			<p><i>elassions</i></p>
			<p><i>elassiez</i></p>
			<p><i>elassent</i></p>
		</imparfait>
	</subjonctif>
	<imperatif>
		<present>
			<p><i>elle</i></p>
			<p><i>elons</i></p>
			<p><i>elez</i></p>
		</present>
	</imperatif>
	<participe>
		<present>
			<p><i>elant</i></p>
		</present>
		<passe>
			<p><i>elé</i></p>
			<p><i>elés</i></p>
			<p><i>elée</i></p>
			<p><i>elées</i></p>
		</passe>
	</participe>
</template>

<template name="p:eler">
	<infinitif>
		<present>
			<p><i>eler</i></p>
		</present>
	</infinitif>
	<indicatif>
		<present>
			<p><i>èle</i></p>
			<p><i>èles</i></p>
			<p><i>èle</i></p>
			<p><i>elons</i></p>
			<p><i>elez</i></p>
			<p><i>èlent</i></p>
		</present>
		<imparfait>
			<p><i>elais</i></p>
			<p><i>elais</i></p>
			<p><i>elait</i></p>
			<p><i>elions</i></p>
			<p><i>eliez</i></p>
			<p><i>elaient</i></p>
		</imparfait>
		<futur>
			<p><i>èlerai</i></p>
			<p><i>èleras</i></p>
			<p><i>èlera</i></p>
			<p><i>èlerons</i></p>
			<p><i>èlerez</i></p>
			<p><i>èleront</i></p>
		</futur>
		<passe-simple>
			<p><i>elai</i></p>
			<p><i>elas</i></p>
			<p><i>ela</i></p>
			<p><i>elâmes</i></p>
			<p><i>elâtes</i></p>
			<p><i>elèrent</i></p>
		</passe-simple>
	</indicatif>
	<conditionnel>
		<present>
			<p><i>èlerais</i></p>
			<p><i>èlerais</i></p>
			<p><i>èlerait</i></p>
			<p><i>èlerions</i></p>
			<p><i>èleriez</i></p>
			<p><i>èleraient</i></p>
		</present>
	</conditionnel>
	<subjonctif>
		<present>
			<p><i>èle</i></p>
			<p><i>èles</i></p>
			<p><i>èle</i></p>
			<p><i>elions</i></p>
			<p><i>eliez</i></p>
			<p><i>èlent</i></p>
		</present>
		<imparfait>
			<p><i>elasse</i></p>
			<p><i>elasses</i></p>
			<p><i>elât</i></p>
			<p><i>elassions</i></p>
			<p><i>elassiez</i></p>
			<p><i>elassent</i></p>
		</imparfait>
	</subjonctif>
	<imperatif>
		<present>
			<p><i>èle</i></p>
			<p><i>elons</i></p>
			<p><i>elez</i></p>
		</present>
	</imperatif>
	<participe>
		<present>
			<p><i>elant</i></p>
		</present>
		<passe>
			<p><i>elé</i></p>
			<p><i>elés</i></p>
			<p><i>elée</i></p>
			<p><i>elées</i></p>
		</passe>
	</participe>
</template>

<template name="j:eter">
	<infinitif>
		<present>
			<p><i>eter</i></p>
		</present>
	</infinitif>
	<indicatif>
		<present>
			<p><i>ette</i></p>
			<p><i>ettes</i></p>
			<p><i>ette</i></p>
			<p><i>etons</i></p>
			<p><i>etez</i></p>
			<p><i>ettent</i></p>
		</present>
		<imparfait>
			<p><i>etais</i></p>
			<p><i>etais</i></p>
			<p><i>etait</i></p>
			<p><i>etions</i></p>
			<p><i>etiez</i></p>
			<p><i>etaient</i></p>
		</imparfait>
		<futur>
			<p><i>etterai</i></p>
			<p><i>etteras</i></p>
			<p><i>ettera</i></p>
			<p><i>etterons</i></p>
			<p><i>etterez</i></p>
			<p><i>etteront</i></p>
		</futur>
		<passe-simple>
			<p><i>etai</i></p>
			<p><i>etas</i></p>
			<p><i>eta</i></p>
			<p><i>etâmes</i></p>
			<p><i>etâtes</i></p>
			<p><i>etèrent</i></p>
		</passe-simple>
	</indicatif>
	<conditionnel>
		<present>
			<p><i>etterais</i></p>
			<p><i>etterais</i></p>
			<p><i>etterait</i></p>
			<p><i>etterions</i></p>
			<p><i>etteriez</i></p>
			<p><i>etteraient</i></p>
		</present>
	</conditionnel>
	<subjonctif>
		<present>
			<p><i>ette</i></p>
			<p><i>ettes</i></p>
			<p><i>ette</i></p>
			<p><i>etions</i></p>
			<p><i>etiez</i></p>
			<p><i>ettent</i></p>
		</present>
		<imparfait>
			<p><i>etasse</i></p>
			<p><i>etasses</i></p>
			<p><i>etât</i></p>
			<p><i>etassions</i></p>
			<p><i>etassiez</i></p>
			<p><i>etassent</i></p>
		</imparfait>
	</subjonctif>
	<imperatif>
		<present>
			<p><i>ette</i></p>
			<p><i>etons</i></p>
			<p><i>etez</i></p>
		</present>
	</imperatif>
	<participe>
		<present>
			<p><i>etant</i></p>
		</present>
		<passe>
			<p><i>eté</i></p>
			<p><i>etés</i></p>
			<p><i>etée</i></p>
			<p><i>etées</i></p>
		</passe>
	</participe>
</template>

<template name="ach:eter">
	<infinitif>
		<present>
			<p><i>eter</i></p>
		</present>
	</infinitif>
	<indicatif>
		<present>
			<p><i>ète</i></p>
			<p><i>ètes</i></p>
			<p><i>ète</i></p>
			<p><i>etons</i></p>
			<p><i>etez</i></p>
			<p><i>ètent</i></p>
		</present>
		<imparfait>
			<p><i>etais</i></p>
			<p><i>etais</i></p>
			<p><i>etait</i></p>
			<p><i>etions</i></p>
			<p><i>etiez</i></p>
			<p><i>etaient</i></p>
		</imparfait>
		<futur>
			<p><i>èterai</i></p>
			<p><i>èteras</i></p>
			<p><i>ètera</i></p>
			<p><i>èterons</i></p>
			<p><i>èterez</i></p>
			<p><i>èteront</i></p>
		</futur>
		<passe-simple>
			<p><i>etai</i></p>
			<p><i>etas</i></p>
			<p><i>eta</i></p>
			<p><i>etâmes</i></p>
			<p><i>etâtes</i></p>
			<p><i>etèrent</i></p>
		</passe-simple>
	</indicatif>
	<conditionnel>
		<present>
			<p><i>èterais</i></p>
			<p><i>èterais</i></p>
			<p><i>èterait</i></p>
			<p><i>èterions</i></p>
			<p><i>èteriez</i></p>
			<p><i>èteraient</i></p>
		</present>
	</conditionnel>
	<subjonctif>
		<present>
			<p><i>ète</i></p>
			<p><i>ètes</i></p>
			<p><i>ète</i></p>
			<p><i>etions</i></p>
			<p><i>etiez</i></p>
			<p><i>ètent</i></p>
		</present>
		<imparfait>
			<p><i>etasse</i></p>
			<p><i>etasses</i></p>
			<p><i>etât</i></p>
			<p><i>etassions</i></p>
			<p><i>etassiez</i></p>
			<p><i>etassent</i></p>
		</imparfait>
	</subjonctif>
	<imperatif>
		<present>
			<p><i>ète</i></p>
			<p><i>etons</i></p>
			<p><i>etez</i></p>
		</present>
	</imperatif>
	<participe>
		<present>
			<p><i>etant</i></p>
		</present>
		<passe>
			<p><i>eté</i></p>
			<p><i>etés</i></p>
			<p><i>etée</i></p>
			<p><i>etées</i></p>
		</passe>
	</participe>
</template>

<template name="héb:éter">
	<infinitif>
		<present>
			<p><i>éter</i></p>
		</present>
	</infinitif>
	<indicatif>
		<present>
			<p><i>ète</i></p>
			<p><i>ètes</i></p>
			<p><i>ète</i></p>
			<p><i>étons</i></p>
			<p><i>étez</i></p>
			<p><i>ètent</i></p>
		</present>
		<imparfait>
			<p><i>étais</i></p>
			<p><i>étais</i></p>
			<p><i>était</i></p>
			<p><i>étions</i></p>
			<p><i>étiez</i></p>
			<p><i>étaient</i></p>
		</imparfait>
		<futur>
			<p><i>èterai</i></p>
			<p><i>èteras</i></p>
			<p><i>ètera</i></p>
			<p><i>èterons</i></p>
			<p><i>èterez</i></p>
			<p><i>èteront</i></p>
		</futur>
		<passe-simple>
			<p><i>étai</i></p>
			<p><i>étas</i></p>
			<p><i>éta</i></p>
			<p><i>étâmes</i></p>
			<p><i>étâtes</i></p>
			<p><i>étèrent</i></p>
		</passe-simple>
	</indicatif>
	<conditionnel>
		<present>
			<p><i>èterais</i></p>
			<p><i>èterais</i></p>
			<p><i>èterait</i></p>
			<p><i>èterions</i></p>
			<p><i>èteriez</i></p>
			<p><i>èteraient</i></p>
		</present>
	</conditionnel>
	<subjonctif>
		<present>
			<p><i>ète</i></p>
			<p><i>ètes</i></p>
			<p><i>ète</i></p>
			<p><i>étions</i></p>
			<p><i>étiez</i></p>
			<p><i>ètent</i></p>
		</present>
		<imparfait>
			<p><i>étasse</i></p>
			<p><i>étasses</i></p>
			<p><i>étât</i></p>
			<p><i>étassions</i></p>
			<p><i>étassiez</i></p>
			<p><i>étassent</i></p>
		</imparfait>
	</subjonctif>
	<imperatif>
		<present>
			<p><i>ète</i></p>
			<p><i>étons</i></p>
			<p><i>étez</i></p>
		</present>
	</imperatif>
	<participe>
		<present>
			<p><i>étant</i></p>
		</present>
		<passe>
			<p><i>été</i></p>
			<p><i>étés</i></p>
			<p><i>étée</i></p>
			<p><i>étées</i></p>
		</passe>
	</participe>
</template>

<template name="s:emer">
	<infinitif>
		<present>
			<p><i>emer</i></p>
		</present>
	</infinitif>
	<indicatif>
		<present>
			<p><i>ème</i></p>
			<p><i>èmes</i></p>
			<p><i>ème</i></p>
			<p><i>emons</i></p>
			<p><i>emez</i></p>
			<p><i>èment</i></p>
		</present>
		<imparfait>
			<p><i>emais</i></p>
			<p><i>emais</i></p>
			<p><i>emait</i></p>
			<p><i>emions</i></p>
			<p><i>emiez</i></p>
			<p><i>emaient</i></p>
		</imparfait>
		<futur>
			<p><i>èmerai</i></p>
			<p><i>èmeras</i></p>
			<p><i>èmera</i></p>
			<p><i>èmerons</i></p>
			<p><i>èmerez</i></p>
			<p><i>èmeront</i></p>
		</futur>
		<passe-simple>
			<p><i>emai</i></p>
			<p><i>emas</i></p>
			<p><i>ema</i></p>
			<p><i>emâmes</i></p>
			<p><i>emâtes</i></p>
			<p><i>emèrent</i></p>
		</passe-simple>
	</indicatif>
	<conditionnel>
		<present>
			<p><i>èmerais</i></p>
			<p><i>èmerais</i></p>
			<p><i>èmerait</i></p>
			<p><i>èmerions</i></p>
			<p><i>èmeriez</i></p>
			<p><i>èmeraient</i></p>
		</present>
	</conditionnel>
	<subjonctif>
		<present>
			<p><i>ème</i></p>
			<p><i>èmes</i></p>
			<p><i>ème</i></p>
			<p><i>emions</i></p>
			<p><i>emiez</i></p>
			<p><i>èment</i></p>
		</present>
		<imparfait>
			<p><i>emasse</i></p>
			<p><i>emasses</i></p>
			<p><i>emât</i></p>
			<p><i>emassions</i></p>
			<p><i>emassiez</i></p>
			<p><i>emassent</i></p>
		</imparfait>
	</subjonctif>
	<imperatif>
		<present>
			<p><i>ème</i></p>
			<p><i>emons</i></p>
			<p><i>emez</i></p>
		</present>
	</imperatif>
	<participe>
		<present>
			<p><i>emant</i></p>
		</present>
		<passe>
			<p><i>emé</i></p>
			<p><i>emés</i></p>
			<p><i>emée</i></p>
			<p><i>emées</i></p>
		</passe>
	</participe>
</template>

<template name="l:éguer">
	<infinitif>
		<present>
			<p><i>éguer</i></p>
		</present>
	</infinitif>
	<indicatif>
		<present>
			<p><i>ègue</i></p>
			<p><i>ègues</i></p>
			<p><i>ègue</i></p>
			<p><i>éguons</i></p>
			<p><i>éguez</i></p>
			<p><i>èguent</i></p>
		</present>
		<imparfait>
			<p><i>éguais</i></p>
			<p><i>éguais</i></p>
			<p><i>éguait</i></p>
			<p><i>éguions</i></p>
			<p><i>éguiez</i></p>
			<p><i>éguaient</i></p>
		</imparfait>
		<futur>
			<p><i>èguerai</i></p>
			<p><i>ègueras</i></p>
			<p><i>èguera</i></p>
			<p><i>èguerons</i></p>
			<p><i>èguerez</i></p>
			<p><i>ègueront</i></p>
		</futur>
		<passe-simple>
			<p><i>éguai</i></p>
			<p><i>éguas</i></p>
			<p><i>égua</i></p>
			<p><i>éguâmes</i></p>
			<p><i>éguâtes</i></p>
			<p><i>éguèrent</i></p>
		</passe-simple>
	</indicatif>
	<conditionnel>
		<present>
			<p><i>èguerais</i></p>
			<p><i>èguerais</i></p>
			<p><i>èguerait</i></p>
			<p><i>èguerions</i></p>
			<p><i>ègueriez</i></p>
			<p><i>ègueraient</i></p>
		</present>
	</conditionnel>
	<subjonctif>
		<present>
			<p><i>ègue</i></p>
			<p><i>ègues</i></p>
			<p><i>ègue</i></p>
			<p><i>éguions</i></p>
			<p><i>éguiez</i></p>
			<p><i>èguent</i></p>
		</present>
		<imparfait>
			<p><i>éguasse</i></p>
			<p><i>éguasses</i></p>
			<p><i>éguât</i></p>
			<p><i>éguassions</i></p>
			<p><i>éguassiez</i></p>
			<p><i>éguassent</i></p>
		</imparfait>
	</subjonctif>
	<imperatif>
		<present>
			<p><i>ègue</i></p>
			<p><i>éguons</i></p>
			<p><i>éguez</i></p>
		</present>
	</imperatif>
	<participe>
		<present>
			<p><i>éguant</i></p>
		</present>
		<passe>
			<p><i>égué</i></p>
			<p><i>égués</i></p>
			<p><i>éguée</i></p>
			<p><i>éguées</i></p>
		</passe>
	</participe>
</template>

<template name="diss:équer">
	<infinitif>
		<present>
			<p><i>équer</i></p>
		</present>
	</infinitif>
	<indicatif>
		<present>
			<p><i>èque</i></p>
			<p><i>èques</i></p>
			<p><i>èque</i></p>
			<p><i>équons</i></p>
			<p><i>équez</i></p>
			<p><i>èquent</i></p>
		</present>
		<imparfait>
			<p><i>équais</i></p>
			<p><i>équais</i></p>
			<p><i>équait</i></p>
			<p><i>équions</i></p>
			<p><i>équiez</i></p>
			<p><i>équaient</i></p>
		</imparfait>
		<futur>
			<p><i>èquerai</i></p>
			<p><i>èqueras</i></p>
			<p><i>èquera</i></p>
			<p><i>èquerons</i></p>
			<p><i>èquerez</i></p>
			<p><i>èqueront</i></p>
		</futur>
		<passe-simple>
			<p><i>équai</i></p>
			<p><i>équas</i></p>
			<p><i>équa</i></p>
			<p><i>équâmes</i></p>
			<p><i>équâtes</i></p>
			<p><i>équèrent</i></p>
		</passe-simple>
	</indicatif>
	<conditionnel>
		<present>
			<p><i>èquerais</i></p>
			<p><i>èquerais</i></p>
			<p><i>èquerait</i></p>
			<p><i>èquerions</i></p>
			<p><i>èqueriez</i></p>
			<p><i>èqueraient</i></p>
		</present>
	</conditionnel>
	<subjonctif>
		<present>
			<p><i>èque</i></p>
			<p><i>èques</i></p>
			<p><i>èque</i></p>
			<p><i>équions</i></p>
			<p><i>équiez</i></p>
			<p><i>èquent</i></p>
		</present>
		<imparfait>
			<p><i>équasse</i></p>
			<p><i>équasses</i></p>
			<p><i>équât</i></p>
			<p><i>équassions</i></p>
			<p><i>équassiez</i></p>
			<p><i>équassent</i></p>
		</imparfait>
	</subjonctif>
	<imperatif>
		<present>
			<p><i>èque</i></p>
			<p><i>équons</i></p>
			<p><i>équez</i></p>
		</present>
	</imperatif>
	<participe>
		<present>
			<p><i>équant</i></p>
		</present>
		<passe>
			<p><i>équé</i></p>
			<p><i>équés</i></p>
			<p><i>équée</i></p>
			<p><i>équées</i></p>
		</passe>
	</participe>
</template>

<template name="rév:éler">
	<infinitif>
		<present>
			<p><i>éler</i></p>
		</present>
	</infinitif>
	<indicatif>
		<present>
			<p><i>èle</i></p>
			<p><i>èles</i></p>
			<p><i>èle</i></p>
			<p><i>élons</i></p>
			<p><i>élez</i></p>
			<p><i>èlent</i></p>
		</present>
		<imparfait>
			<p><i>élais</i></p>
			<p><i>élais</i></p>
			<p><i>élait</i></p>
			<p><i>élions</i></p>
			<p><i>éliez</i></p>
			<p><i>élaient</i></p>
		</imparfait>
		<futur>
			<p><i>élerai</i><i>èlerai</i></p>
			<p><i>éleras</i><i>èleras</i></p>
			<p><i>élera</i><i>èlera</i></p>
			<p><i>élerons</i><i>èlerons</i></p>
			<p><i>élerez</i><i>èlerez</i></p>
			<p><i>éleront</i><i>èleront</i></p>
		</futur>
		<passe-simple>
			<p><i>élai</i></p>
			<p><i>élas</i></p>
			<p><i>éla</i></p>
			<p><i>élâmes</i></p>
			<p><i>élâtes</i></p>
			<p><i>élèrent</i></p>
		</passe-simple>
	</indicatif>
	<conditionnel>
		<present>
			<p><i>élerais</i><i>èlerais</i></p>
			<p><i>élerais</i><i>èlerais</i></p>
			<p><i>élerait</i><i>èlerait</i></p>
			<p><i>élerions</i><i>èlerions</i></p>
			<p><i>éleriez</i><i>èleriez</i></p>
			<p><i>éleraient</i><i>èleraient</i></p>
		</present>
	</conditionnel>
	<subjonctif>
		<present>
			<p><i>èle</i></p>
			<p><i>èles</i></p>
			<p><i>èle</i></p>
			<p><i>élions</i></p>
			<p><i>éliez</i></p>
			<p><i>èlent</i></p>
		</present>
		<imparfait>
			<p><i>élasse</i></p>
			<p><i>élasses</i></p>
			<p><i>élât</i></p>
			<p><i>élassions</i></p>
			<p><i>élassiez</i></p>
			<p><i>élassent</i></p>
		</imparfait>
	</subjonctif>
	<imperatif>
		<present>
			<p><i>èle</i></p>
			<p><i>élons</i></p>
			<p><i>élez</i></p>
		</present>
	</imperatif>
	<participe>
		<present>
			<p><i>élant</i></p>
		</present>
		<passe>
			<p><i>élé</i></p>
			<p><i>élés</i></p>
			<p><i>élée</i></p>
			<p><i>élées</i></p>
		</passe>
	</participe>
</template>

<template name="imp:étrer">
	<infinitif>
		<present>
			<p><i>étrer</i></p>
		</present>
	</infinitif>
	<indicatif>
		<present>
			<p><i>ètre</i></p>
			<p><i>ètres</i></p>
			<p><i>ètre</i></p>
			<p><i>étrons</i></p>
			<p><i>étrez</i></p>
			<p><i>ètrent</i></p>
		</present>
		<imparfait>
			<p><i>étrais</i></p>
			<p><i>étrais</i></p>
			<p><i>étrait</i></p>
			<p><i>étrions</i></p>
			<p><i>étriez</i></p>
			<p><i>étraient</i></p>
		</imparfait>
		<futur>
			<p><i>étrerai</i><i>ètrerai</i></p>
			<p><i>étreras</i><i>ètreras</i></p>
			<p><i>étrera</i><i>ètrera</i></p>
			<p><i>étrerons</i><i>ètrerons</i></p>
			<p><i>étrerez</i><i>ètrerez</i></p>
			<p><i>étreront</i><i>ètreront</i></p>
		</futur>
		<passe-simple>
			<p><i>étrai</i></p>
			<p><i>étras</i></p>
			<p><i>étra</i></p>
			<p><i>étrâmes</i></p>
			<p><i>étrâtes</i></p>
			<p><i>étrèrent</i></p>
		</passe-simple>
	</indicatif>
	<conditionnel>
		<present>
			<p><i>étrerais</i><i>ètrerais</i></p>
			<p><i>étrerais</i><i>ètrerais</i></p>
			<p><i>étrerait</i><i>ètrerait</i></p>
			<p><i>étrerions</i><i>ètrerions</i></p>
			<p><i>étreriez</i><i>ètreriez</i></p>
			<p><i>étreraient</i><i>ètreraient</i></p>
		</present>
	</conditionnel>
	<subjonctif>
		<present>
			<p><i>ètre</i></p>
			<p><i>ètres</i></p>
			<p><i>ètre</i></p>
			<p><i>étrions</i></p>
			<p><i>étriez</i></p>
			<p><i>ètrent</i></p>
		</present>
		<imparfait>
			<p><i>étrasse</i></p>
			<p><i>étrasses</i></p>
			<p><i>étrât</i></p>
			<p><i>étrassions</i></p>
			<p><i>étrassiez</i></p>
			<p><i>étrassent</i></p>
		</imparfait>
	</subjonctif>
	<imperatif>
		<present>
			<p><i>ètre</i></p>
			<p><i>étrons</i></p>
			<p><i>étrez</i></p>
		</present>
	</imperatif>
	<participe>
		<present>
			<p><i>étrant</i></p>
		</present>
		<passe>
			<p><i>étré</i></p>
			<p><i>étrés</i></p>
			<p><i>étrée</i></p>
			<p><i>étrées</i></p>
		</passe>
	</participe>
</template>

<template name="r:égler">
	<infinitif>
		<present>
			<p><i>égler</i></p>
		</present>
	</infinitif>
	<indicatif>
		<present>
			<p><i>ègle</i></p>
			<p><i>ègles</i></p>
			<p><i>ègle</i></p>
			<p><i>églons</i></p>
			<p><i>églez</i></p>
			<p><i>èglent</i></p>
		</present>
		<imparfait>
			<p><i>églais</i></p>
			<p><i>églais</i></p>
			<p><i>églait</i></p>
			<p><i>églions</i></p>
			<p><i>égliez</i></p>
			<p><i>églaient</i></p>
		</imparfait>
		<futur>
			<p><i>églerai</i><i>èglerai</i></p>
			<p><i>égleras</i><i>ègleras</i></p>
			<p><i>églera</i><i>èglera</i></p>
			<p><i>églerons</i><i>èglerons</i></p>
			<p><i>églerez</i><i>èglerez</i></p>
			<p><i>égleront</i><i>ègleront</i></p>
		</futur>
		<passe-simple>
			<p><i>églai</i></p>
			<p><i>églas</i></p>
			<p><i>égla</i></p>
			<p><i>églâmes</i></p>
			<p><i>églâtes</i></p>
			<p><i>églèrent</i></p>
		</passe-simple>
	</indicatif>
	<conditionnel>
		<present>
			<p><i>églerais</i><i>èglerais</i></p>
			<p><i>églerais</i><i>èglerais</i></p>
			<p><i>églerait</i><i>èglerait</i></p>
			<p><i>églerions</i><i>èglerions</i></p>
			<p><i>égleriez</i><i>ègleriez</i></p>
			<p><i>égleraient</i><i>ègleraient</i></p>
		</present>
	</conditionnel>
	<subjonctif>
		<present>
			<p><i>ègle</i></p>
			<p><i>ègles</i></p>
			<p><i>ègle</i></p>
			<p><i>églions</i></p>
			<p><i>égliez</i></p>
			<p><i>èglent</i></p>
		</present>
		<imparfait>
			<p><i>églasse</i></p>